name: Remove genezio.yaml on Push to Main

on:
  push:
    branches:
      - main

jobs:
  remove-genezio-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if genezio.yaml was added
        id: genezio_check
        run: |
          if git diff --name-status HEAD^ HEAD | grep -q "^A\s\+genezio.yaml"; then
            echo "genezio.yaml added in the latest commit"
            echo "::set-output name=file_added::true"
          else
            echo "genezio.yaml not added in the latest commit"
            echo "::set-output name=file_added::false"
          fi

      - name: Remove genezio.yaml and commit
        if: steps.genezio_check.outputs.file_added == 'true'
        run: |
          git rm genezio.yaml
          git commit -m "Remove genezio.yaml"
          git push
